feat: change namespaces
OperatorIsRequiredException: namespace changed from DynamicFilters.Exceptions to DynamicFilters
TypeExtensions: namespace changed from DynamicFilters.Core to DynamicFilters